routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/pegawai', 'HomePegawaiController@index')->name('homepegawai');
Route::get('/homeutama', 'HomeUtamaController@index')->name('homeutama');
Route::get('/bukuutama', 'HomeUtamaController@buku')->name('bukuutama');
Route::get('/homeutama/data', 'HomeUtamaController@listdata')->name('homeutama.data');


Route::get('/kategori/data', 'KategoriController@listdata')->name('kategori.data');
    Route::resource('/kategori','KategoriController',[
        'except' => 'show'
]);

Route::get('/pengarang/data', 'PengarangController@listdata')->name('pengarang.data');
    Route::resource('/pengarang','PengarangController',[
        'except' => 'show'
]);

Route::get('/negara/data', 'NegaraController@listdata')->name('negara.data');
    Route::resource('/negara','NegaraController',[
        'except' => 'show'
]);

Route::get('/kota/data', 'KotaController@listdata')->name('kota.data');
    Route::resource('/kota','KotaController',[
        'except' => 'show'
]);

Route::get('/penerbit/data', 'PenerbitController@listdata')->name('penerbit.data');
    Route::resource('/penerbit','PenerbitController',[
        'except' => 'show'
]);

Route::get('/buku/data', 'BukuController@listdata')->name('buku.data');
    Route::resource('/buku','BukuController',[
        'except' => 'show'
]);

app/Negara.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Negara extends Model
{
  protected $table = 'tb_negara';
  protected $primaryKey = 'negara_id';
}

app/Http/Controllers/NegaraController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DataTables;
use App\Negara;
use JsValidator;
use Illuminate\Validation\Rule;

class NegaraController extends Controller
{
  public function index()
  {
    return view('negara.negara_index');
  }

  public function listData()
  {
    $negara = Negara::all();
    $no = 0;
    $data = array();
    foreach($negara as $list){
      $no ++;
      $row = array();
      $row[] = $no;
      $row[] = 'NG0'.$list->negara_id;
      $row[] = $list->negara_nama;
      $row[] = '<div class="btn-group">
              <a href="' . route('negara.edit', $list->negara_id) . '" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
              <a onclick="deleteData('.$list->negara_id.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a></div>';
      $data[] = $row;
    }
    $output = array("data" => $data);
    return response()->json($output);
  }

  public function rulesCreate()
  {
    $rules = [
        'negara_nama' => 'required|unique:tb_negara,negara_nama'
      ];
    return $rules;
  }

  public function messages()
  {
    return [
        'negara_nama.required' => 'Bidang isian nama negara wajib diisi.',
    ];
  }

  public function create()
  {
    return view('negara.negara_create',[
      'JsValidator' => JsValidator::make($this->rulesCreate()),
    ]);
  }

  public function store(Request $request)
  {
    // $data = $this->validate($request,$this->rulesCreate());
    $db = new Negara;
    $db->negara_nama = $request->negara_nama;
    if ($db->save()) {
      return redirect()->route('negara.index');
    }
  }

  // public function rulesEdit($id)
  // {
  //   return [
  //     'nama_agama' => [
  //       'required',
  //       Rule::unique('tb_agama','agama_nama')->ignore($id,'agama_id'),
  //     ],
  //   ];
  // }
  //
  public function edit($id)
  {
    return view('negara.negara_edit',[
      // 'JsValidator' => JsValidator::make($this->rulesEdit($id)),
      'data' => Negara::find($id),
    ]);
  }

  public function update(Request $request , $id)
  {
    // $data = $this->validate($request,$this->rulesEdit($id));
    $db = Negara::find($id);
    $db->negara_nama = $request->negara_nama;
    if($db->save()){
        return redirect()->route('negara.index');
    }
  }

  public function destroy($id)
  {
    Negara::destroy($id);
    return redirect()->route('negara.index');
  }
}

resources/views/negara/negara_create.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Negara
@endsection

@section('breadcrumb')
   @parent
   <li>Negara</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <form class="form-horizontal" id="form-input" method="post" action="{{ route('negara.store') }}">
          {{ csrf_field() }} {{ method_field('POST') }}
          <div class="modal-body">
          <div class="form-group">
             <label for="nama" class="col-md-3 control-label">Nama Negara</label>
             <div class="col-md-6">
                <input id="negara_nama" type="text" class="form-control" name="negara_nama" required>
                <span class="help-block with-errors"></span>
             </div>
          </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
             <a href="{{ route('negara.index') }}" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Batal</a>             
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')

@endsection

resources/views/negara/negara_edit.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Negara
@endsection

@section('breadcrumb')
@parent
   <li>Negara</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <form class="form-horizontal" id="form-input" method="post" action="{{ route('negara.update',$data->negara_id) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}
          <div class="modal-body">
          <div class="form-group">
             <label for="nama" class="col-md-3 control-label">Nama Negara</label>
             <div class="col-md-6">
                <input id="negara_nama" type="text" class="form-control" name="negara_nama" value="{{ $data->negara_nama }}" required>
                <span class="help-block with-errors"></span>
             </div>
          </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
             <a href="{{ route('negara.index') }}" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Batal</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')

@endsection

resources/views/negara/negara_index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Negara
@endsection

@section('breadcrumb')
   @parent
   <li>Negara</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a href="{{ route('negara.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">

  <form method="post" id="form-produk">
  {{ csrf_field() }}
      <table class="table table-striped">
      <thead>
         <tr>
            <th width="20">No</th>
              <th>Kode Negara</th>
              <th>Nama Negara</th>
            <th width="100">Aksi</th>
         </tr>
      </thead>
      <tbody></tbody>
      </table>
      </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
    $(function() {
        table = $('.table').DataTable({
            "processing" : true,
            "ajax" : {
            "url" : "{{ route('negara.data') }}",
            "type" : "GET"
            }
        });
    });

    function deleteData(id){
       if(confirm("Apakah yakin data akan dihapus?")){
         $.ajax({
           url : "negara/"+id,
           type : "POST",
           data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
           success : function(data){
             table.ajax.reload();
           },
           error : function(){
             alert("Tidak dapat menghapus data!");
           }
         });
       }
    }
</script>
@endsection