routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/pegawai', 'HomePegawaiController@index')->name('homepegawai');
Route::get('/homeutama', 'HomeUtamaController@index')->name('homeutama');
Route::get('/bukuutama', 'HomeUtamaController@buku')->name('bukuutama');
Route::get('/homeutama/data', 'HomeUtamaController@listdata')->name('homeutama.data');


Route::get('/kategori/data', 'KategoriController@listdata')->name('kategori.data');
    Route::resource('/kategori','KategoriController',[
        'except' => 'show'
]);

Route::get('/pengarang/data', 'PengarangController@listdata')->name('pengarang.data');
    Route::resource('/pengarang','PengarangController',[
        'except' => 'show'
]);

Route::get('/negara/data', 'NegaraController@listdata')->name('negara.data');
    Route::resource('/negara','NegaraController',[
        'except' => 'show'
]);

Route::get('/kota/data', 'KotaController@listdata')->name('kota.data');
    Route::resource('/kota','KotaController',[
        'except' => 'show'
]);

Route::get('/penerbit/data', 'PenerbitController@listdata')->name('penerbit.data');
    Route::resource('/penerbit','PenerbitController',[
        'except' => 'show'
]);

Route::get('/buku/data', 'BukuController@listdata')->name('buku.data');
    Route::resource('/buku','BukuController',[
        'except' => 'show'
]);

app/Pengarang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengarang extends Model
{
  protected $table = 'tb_pengarang';
  protected $primaryKey = 'pengarang_id';
}

app/Http/Controllers/PengarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DataTables;
use App\Pengarang;
use JsValidator;
use Illuminate\Validation\Rule;

class PengarangController extends Controller
{
  public function index()
  {
    return view('pengarang.pengarang_index');
  }

  public function listData()
  {
    $pengarang = Pengarang::all();
    $no = 0;
    $data = array();
    foreach($pengarang as $list){
      $no ++;
      $row = array();
      $row[] = $no;
      $row[] = 'PG0'.$list->pengarang_id;
      $row[] = $list->pengarang_nama;
      $row[] = '<div class="btn-group">
              <a href="' . route('pengarang.edit', $list->pengarang_id) . '" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
              <a onclick="deleteData('.$list->pengarang_id.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a></div>';
      $data[] = $row;
    }
    $output = array("data" => $data);
    return response()->json($output);
  }

  public function rulesCreate()
  {
    $rules = [
        'pengarang_nama' => 'required|unique:tb_pengarang,pengarang_nama'
      ];
    return $rules;
  }

  public function messages()
  {
    return [
        'pengarang_nama.required' => 'Bidang isian nama pengarang wajib diisi.',
    ];
  }

  public function create()
  {
    return view('pengarang.pengarang_create',[
      'JsValidator' => JsValidator::make($this->rulesCreate()),
    ]);
  }

  public function store(Request $request)
  {
    // $data = $this->validate($request,$this->rulesCreate());
    $db = new Pengarang;
    $db->pengarang_nama = $request->pengarang_nama;
    if ($db->save()) {
      return redirect()->route('pengarang.index');
    }
  }

  // public function rulesEdit($id)
  // {
  //   return [
  //     'nama_agama' => [
  //       'required',
  //       Rule::unique('tb_agama','agama_nama')->ignore($id,'agama_id'),
  //     ],
  //   ];
  // }
  //
  public function edit($id)
  {
    return view('pengarang.pengarang_edit',[
      // 'JsValidator' => JsValidator::make($this->rulesEdit($id)),
      'data' => Pengarang::find($id),
    ]);
  }

  public function update(Request $request , $id)
  {
    // $data = $this->validate($request,$this->rulesEdit($id));
    $db = Pengarang::find($id);
    $db->pengarang_nama = $request->pengarang_nama;
    if($db->save()){
        return redirect()->route('pengarang.index');
    }
  }

  public function destroy($id)
  {
    Pengarang::destroy($id);
    return redirect()->route('pengarang.index');
  }
}

resources/views/pengarang/pengarang_create.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Pengarang
@endsection

@section('breadcrumb')
   @parent
   <li>Pengarang</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <form class="form-horizontal" id="form-input" method="post" action="{{ route('pengarang.store') }}">
          {{ csrf_field() }} {{ method_field('POST') }}
          <div class="modal-body">
          <div class="form-group">
             <label for="nama" class="col-md-3 control-label">Nama Pengarang</label>
             <div class="col-md-6">
                <input id="pengarang_nama" type="text" class="form-control" name="pengarang_nama" required>
                <span class="help-block with-errors"></span>
             </div>
          </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
             <a href="{{ route('pengarang.index') }}" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Batal</a>             
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')

@endsection

resources/views/pengarang/pengarang_edit.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Pengarang
@endsection

@section('breadcrumb')
   @parent
   <li>Pengarang</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <form class="form-horizontal" id="form-input" method="post" action="{{ route('pengarang.update',$data->pengarang_id) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}
          <div class="modal-body">
          <div class="form-group">
             <label for="nama" class="col-md-3 control-label">Nama Pengarang</label>
             <div class="col-md-6">
                <input id="pengarang_nama" type="text" class="form-control" name="pengarang_nama" value="{{ $data->pengarang_nama }}" required>
                <span class="help-block with-errors"></span>
             </div>
          </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
             <a href="{{ route('pengarang.index') }}" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Batal</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')

@endsection

resources/views/pengarang/pengarang_index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Pengarang
@endsection

@section('breadcrumb')
   @parent
   <li>Pengarang</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a href="{{ route('pengarang.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">

  <form method="post" id="form-produk">
  {{ csrf_field() }}
      <table class="table table-striped">
      <thead>
         <tr>
            <th width="20">No</th>
              <th>Kode Pengarang</th>
              <th>Nama Pengarang</th>
            <th width="100">Aksi</th>
         </tr>
      </thead>
      <tbody></tbody>
      </table>
      </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
    $(function() {
        table = $('.table').DataTable({
            "processing" : true,
            "ajax" : {
            "url" : "{{ route('pengarang.data') }}",
            "type" : "GET"
            }
        });
    });

    function deleteData(id){
       if(confirm("Apakah yakin data akan dihapus?")){
         $.ajax({
           url : "pengarang/"+id,
           type : "POST",
           data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
           success : function(data){
             table.ajax.reload();
           },
           error : function(){
             alert("Tidak dapat menghapus data!");
           }
         });
       }
    }
</script>
@endsection