routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/pegawai', 'HomePegawaiController@index')->name('homepegawai');
Route::get('/homeutama', 'HomeUtamaController@index')->name('homeutama');
Route::get('/bukuutama', 'HomeUtamaController@buku')->name('bukuutama');
Route::get('/homeutama/data', 'HomeUtamaController@listdata')->name('homeutama.data');


Route::get('/kategori/data', 'KategoriController@listdata')->name('kategori.data');
    Route::resource('/kategori','KategoriController',[
        'except' => 'show'
]);

Route::get('/pengarang/data', 'PengarangController@listdata')->name('pengarang.data');
    Route::resource('/pengarang','PengarangController',[
        'except' => 'show'
]);

Route::get('/negara/data', 'NegaraController@listdata')->name('negara.data');
    Route::resource('/negara','NegaraController',[
        'except' => 'show'
]);

Route::get('/kota/data', 'KotaController@listdata')->name('kota.data');
    Route::resource('/kota','KotaController',[
        'except' => 'show'
]);

Route::get('/penerbit/data', 'PenerbitController@listdata')->name('penerbit.data');
    Route::resource('/penerbit','PenerbitController',[
        'except' => 'show'
]);

Route::get('/buku/data', 'BukuController@listdata')->name('buku.data');
    Route::resource('/buku','BukuController',[
        'except' => 'show'
]);

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'tb_kategori';
    protected $primaryKey = 'kategori_id';
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use DataTables;
use App\Kategori;
use JsValidator;
use Illuminate\Validation\Rule;

class KategoriController extends Controller
{
    public function index()
    {
      return view('kategori.kategori_index');
    }

    public function listData()
    {
      $kategori = Kategori::all();
      $no = 0;
      $data = array();
      foreach($kategori as $list){
        $no ++;
        $row = array();
        $row[] = $no;
        $row[] = 'KT0'.$list->kategori_id;
        $row[] = $list->kategori_nama;
        $row[] = '<div class="btn-group">
                <a href="' . route('kategori.edit', $list->kategori_id) . '" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                <a onclick="deleteData('.$list->kategori_id.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a></div>';
        $data[] = $row;
      }
      $output = array("data" => $data);
      return response()->json($output);
    }

    public function rulesCreate()
    {
      $rules = [
          'kategori_nama' => 'required|unique:tb_kategori,kategori_nama'
        ];
      return $rules;
    }

    public function messages()
    {
      return [
          'kategori_nama.required' => 'Bidang isian nama kategori wajib diisi.',
      ];
    }

    public function create()
    {
      return view('kategori.kategori_create',[
        'JsValidator' => JsValidator::make($this->rulesCreate()),
      ]);
    }

    public function store(Request $request)
    {
      $data = $this->validate($request,$this->rulesCreate());
      $db = new Kategori;
      $db->kategori_nama = $request->kategori_nama;
      if ($db->save()) {
        return redirect()->route('kategori.index');
      }
    }

    // public function rulesEdit($id)
    // {
    //   return [
    //     'nama_agama' => [
    //       'required',
    //       Rule::unique('tb_agama','agama_nama')->ignore($id,'agama_id'),
    //     ],
    //   ];
    // }
    //
    public function edit($id)
    {
      return view('kategori.kategori_edit',[
        // 'JsValidator' => JsValidator::make($this->rulesEdit($id)),
        'data' => Kategori::find($id),
      ]);
    }

    public function update(Request $request , $id)
    {
      // $data = $this->validate($request,$this->rulesEdit($id));
      $db = Kategori::find($id);
      $db->kategori_nama = $request->kategori_nama;
      if($db->save()){
          return redirect()->route('kategori.index');
      }
    }

    public function destroy($id)
    {
      Kategori::destroy($id);
      return redirect()->route('kategori.index');
    }
}

resources/views/kategori/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
   <form class="form-horizontal" data-toggle="validator" method="post">
   {{ csrf_field() }} {{ method_field('POST') }}
   
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title"></h3>
   </div>
            
<div class="modal-body">
   
   <input type="hidden" id="id" name="id">
   <div class="form-group">
      <label for="nama" class="col-md-3 control-label">Nama Produk</label>
      <div class="col-md-6">
         <input id="nama" type="text" class="form-control" name="nama" autofocus required>
         <span class="help-block with-errors"></span>
      </div>
   </div>
   
</div>
   
   <div class="modal-footer">
      <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
      <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
   </div>
      
   </form>

         </div>
      </div>
   </div>

resources/views/kategori/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Kategori
@endsection

@section('breadcrumb')
   @parent
   <li>kategori</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">  

<table class="table table-striped">
<thead>
   <tr>
      <th width="30">No</th>
      <th>Nama Kategori</th>
      <th width="100">Aksi</th>
   </tr>
</thead>
<tbody></tbody>
</table>

      </div>
    </div>
  </div>
</div>

@include('kategori.form')
@endsection

@section('script')
<script type="text/javascript">
var table, save_method;
$(function(){
   table = $('.table').DataTable({
     "processing" : true,
     "ajax" : {
       "url" : "{{ route('kategori.data') }}",
       "type" : "GET"
     }
   }); 
   
   $('#modal-form form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
         var id = $('#id').val();
         if(save_method == "add") url = "{{ route('kategori.store') }}";
         else url = "kategori/"+id;
         
         $.ajax({
           url : url,
           type : "POST",
           data : $('#modal-form form').serialize(),
           success : function(data){
             $('#modal-form').modal('hide');
             table.ajax.reload();
           },
           error : function(){
             alert("Tidak dapat menyimpan data!");
           }   
         });
         return false;
     }
   });
});

function addForm(){
   save_method = "add";
   $('input[name=_method]').val('POST');
   $('#modal-form').modal('show');
   $('#modal-form form')[0].reset();            
   $('.modal-title').text('Tambah Kategori');
}

function editForm(id){
   save_method = "edit";
   $('input[name=_method]').val('PATCH');
   $('#modal-form form')[0].reset();
   $.ajax({
     url : "kategori/"+id+"/edit",
     type : "GET",
     dataType : "JSON",
     success : function(data){
       $('#modal-form').modal('show');
       $('.modal-title').text('Edit Kategori');
       
       $('#id').val(data.id_kategori);
       $('#nama').val(data.nama_kategori);
       
     },
     error : function(){
       alert("Tidak dapat menampilkan data!");
     }
   });
}

function deleteData(id){
   if(confirm("Apakah yakin data akan dihapus?")){
     $.ajax({
       url : "kategori/"+id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
       success : function(data){
         table.ajax.reload();
       },
       error : function(){
         alert("Tidak dapat menghapus data!");
       }
     });
   }
}
</script>
@endsection

resources/views/kategori/kategori_create.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Kategori
@endsection

@section('breadcrumb')
   @parent
   <li>Kategori</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <form class="form-horizontal" id="form-input" method="post" action="{{ route('kategori.store') }}">
          {{ csrf_field() }} {{ method_field('POST') }}
          <div class="modal-body">
          <div class="form-group">
             <label for="nama" class="col-md-3 control-label">Nama Kategori</label>
             <div class="col-md-6">
                <input id="kategori_nama" type="text" class="form-control" name="kategori_nama" required>
                <span class="help-block with-errors"></span>
             </div>
          </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
             <a href="{{ route('kategori.index') }}" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Batal</a>             
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script src="{{ url('vendor/jsvalidation/js/jsvalidation.min.js' , false) }}" charset="utf-8"></script>
{!! $JsValidator->selector('#form-input') !!}
@endsection

resources/views/kategori/kategori_edit.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Kategori
@endsection

@section('breadcrumb')
   @parent
   <li>Kategori</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <form class="form-horizontal" id="form-input" method="post" action="{{ route('kategori.update',$data->kategori_id) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}
          <div class="modal-body">
          <div class="form-group">
             <label for="nama" class="col-md-3 control-label">Nama Kategori</label>
             <div class="col-md-6">
                <input id="kategori_nama" type="text" class="form-control" name="kategori_nama" value="{{ $data->kategori_nama }}" required>
                <span class="help-block with-errors"></span>
             </div>
          </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
             <a href="{{ route('kategori.index') }}" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Batal</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')

@endsection

resources/views/kategori/kategori_index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Kategori
@endsection

@section('breadcrumb')
   @parent
   <li>Kategori</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a href="{{ route('kategori.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">

  <form method="post" id="form-produk">
  {{ csrf_field() }}
      <table class="table table-striped">
      <thead>
         <tr>
            <th width="20">No</th>
            <th>Kode Kategori</th>
            <th>Nama Kategori</th>
            <th width="100">Aksi</th>
         </tr>
      </thead>
      <tbody></tbody>
      </table>
      </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
    $(function() {
        table = $('.table').DataTable({
            "processing" : true,
            "ajax" : {
            "url" : "{{ route('kategori.data') }}",
            "type" : "GET"
            }
        });
    });

    function deleteData(id){
       if(confirm("Apakah yakin data akan dihapus?")){
         $.ajax({
           url : "kategori/"+id,
           type : "POST",
           data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
           success : function(data){
             table.ajax.reload();
           },
           error : function(){
             alert("Tidak dapat menghapus data!");
           }
         });
       }
    }
</script>
@endsection