routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/pegawai', 'HomePegawaiController@index')->name('homepegawai');
Route::get('/homeutama', 'HomeUtamaController@index')->name('homeutama');
Route::get('/bukuutama', 'HomeUtamaController@buku')->name('bukuutama');
Route::get('/homeutama/data', 'HomeUtamaController@listdata')->name('homeutama.data');


Route::get('/kategori/data', 'KategoriController@listdata')->name('kategori.data');
    Route::resource('/kategori','KategoriController',[
        'except' => 'show'
]);

Route::get('/pengarang/data', 'PengarangController@listdata')->name('pengarang.data');
    Route::resource('/pengarang','PengarangController',[
        'except' => 'show'
]);

Route::get('/negara/data', 'NegaraController@listdata')->name('negara.data');
    Route::resource('/negara','NegaraController',[
        'except' => 'show'
]);

Route::get('/kota/data', 'KotaController@listdata')->name('kota.data');
    Route::resource('/kota','KotaController',[
        'except' => 'show'
]);

Route::get('/penerbit/data', 'PenerbitController@listdata')->name('penerbit.data');
    Route::resource('/penerbit','PenerbitController',[
        'except' => 'show'
]);

Route::get('/buku/data', 'BukuController@listdata')->name('buku.data');
    Route::resource('/buku','BukuController',[
        'except' => 'show'
]);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ config('app.name', 'Laravel') }}</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <link rel="stylesheet" href="{{ asset('public/adminLTE/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/font-awesome/css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/skins/skin-blue.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/plugins/datatables/dataTables.bootstrap.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/plugins/datepicker/datepicker3.css') }}">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

   <!-- Header -->
  <header class="main-header">

    <a href="#" class="logo">
    <span class="logo-lg"><b>Toko</b>Buku</span>
    </a>


    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        </ul>
      </div>
    </nav>
  </header>
  <!-- End Header -->


  <!-- Sidebar -->
  <aside class="main-sidebar">

    <section class="sidebar">
      <ul class="sidebar-menu">
        <li class="header">MENU NAVIGASI</li>

        <li><a href="{{ route('homepegawai') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
        {{-- <li><a href="{{ route('kategori.index') }}"><i class="fa fa-cube"></i> <span>Kategori</span></a></li> --}}
        {{-- <li><a href="{{ route('pengarang.index') }}"><i class="fa fa-cube"></i> <span>Pengarang</span></a></li> --}}
        {{-- <li><a href="{{ route('negara.index') }}"><i class="fa fa-cube"></i> <span>Negara</span></a></li> --}}
        {{-- <li><a href="{{ route('kota.index') }}"><i class="fa fa-cube"></i> <span>Kota</span></a></li> --}}
        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Master Data</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{{ route('kategori.index') }}"><i class="fa fa-bolt"></i> <span>Kategori</span></a></li>
             <li><a href="{{ route('pengarang.index') }}"><i class="fa fa-cab"></i> <span>Pengarang</span></a></li>
             <li><a href="{{ route('negara.index') }}"><i class="fa fa-flag"></i> <span>Negara</span></a></li>
             <li><a href="{{ route('kota.index') }}"><i class="fa fa-flag-o"></i> <span>Kota</span></a></li> 
          </ul>
        </li>
        <li><a href="{{ route('penerbit.index') }}"><i class="fa fa-cube"></i> <span>Penerbit</span></a></li>
        <li><a href="{{ route('buku.index') }}"><i class="fa fa-book"></i> <span>Buku</span></a></li>
        <li><a href="{{ route('home') }}"><i class="fa fa-bars"></i> <span>Back</span></a></li>
      </ul>
    </section>
  </aside>
  <!-- End Sidebar -->

  <!-- Content  -->
  <div class="content-wrapper">
   <section class="content-header">
      <h1>
        @yield('title')
      </h1>
      <ol class="breadcrumb">
        @section('breadcrumb')
        <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
        @show
      </ol>
    </section>

    <section class="content">
        @yield('content')
    </section>
  </div>
  <!-- End Content -->

  <!-- Footer -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      Aplikasi Toko Buku SKNNI
    </div>
    <strong>Copyright &copy; Template by AdminLTE.
  </footer>
  <!-- End Footer -->

<script src="{{ asset('public/adminLTE/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/dist/js/app.min.js') }}"></script>

<script src="{{ asset('public/adminLTE/plugins/chartjs/Chart.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('public/js/validator.min.js') }}"></script>

@yield('script')

</body>
</html>

resources/views/layouts/app_utana.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ config('app.name', 'Laravel') }}</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <link rel="stylesheet" href="{{ asset('public/adminLTE/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/font-awesome/css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/skins/skin-blue.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/plugins/datatables/dataTables.bootstrap.css') }}">
  <link rel="stylesheet" href="{{ asset('public/adminLTE/plugins/datepicker/datepicker3.css') }}">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

   <!-- Header -->
  <header class="main-header">

    <a href="#" class="logo">
    <span class="logo-lg"><b>Toko</b>Buku</span>
    </a>


    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        </ul>
      </div>
    </nav>
  </header>
  <!-- End Header -->


  <!-- Sidebar -->
  <aside class="main-sidebar">

    <section class="sidebar">
      <ul class="sidebar-menu">
        <li class="header">MENU NAVIGASI</li>

        <li><a href="{{ route('homeutama') }}"><i class="fa fa-dashboard"></i> <span>Data Buku</span></a></li>
        <li><a href="{{ route('home') }}"><i class="fa fa-bars"></i> <span>Back</span></a></li>
      </ul>
    </section>
  </aside>
  <!-- End Sidebar -->

  <!-- Content  -->
  <div class="content-wrapper">
   <section class="content-header">
      <h1>
        @yield('title')
      </h1>
      <ol class="breadcrumb">
        @section('breadcrumb')
        <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
        @show
      </ol>
    </section>

    <section class="content">
        @yield('content')
    </section>
  </div>
  <!-- End Content -->

  <!-- Footer -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      Aplikasi Toko Buku SKNNI
    </div>
    <strong>Copyright &copy; Template by AdminLTE.
  </footer>
  <!-- End Footer -->

<script src="{{ asset('public/adminLTE/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/dist/js/app.min.js') }}"></script>

<script src="{{ asset('public/adminLTE/plugins/chartjs/Chart.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('public/js/validator.min.js') }}"></script>

@yield('script')

</body>
</html>